const axios = require("axios");

module.exports = async ({ sock, from, msg, config, body, send }) => {

  const args = body.split(" ").slice(1);
  const prompt = args.join(" ");

  // agar prompt na ho
  if (!prompt) {
    return await send({
      text: `❌ Please provide a prompt!

Example:
.ai cinematic robot, highly detailed, 4k`
    });
  }

  await send({
    text: "🎨 AI Art Generator is generating your masterpiece...\nWait 10-25 seconds."
  });

  try {

    // unique device id
    const deviceId = "session-" + Date.now();

    // login token
    const login = await axios.post(
      "https://api.seaart.io/v1/account/login",
      { type: 16 },
      { headers: { "X-Device-ID": deviceId } }
    );

    const token = login.data?.data?.token;

    if (!token) throw new Error("Auth Failed");

    // create image task
    const createTask = await axios.post(
      "https://api.seaart.io/v1/generate/text-to-img",
      {
        meta: {
          prompt: prompt + ", cinematic, highly detailed, 4k",
          n_iter: 1,
          width: 1024,
          height: 1024,
          aspect: "1:1",
          isHomeTask: true
        }
      },
      {
        headers: {
          Token: token,
          "X-Device-ID": deviceId
        }
      }
    );

    const taskId = createTask.data?.data?.id;
    if (!taskId) throw new Error("Task Creation Failed");

    let imageUrl = null;

    // progress check
    for (let i = 0; i < 20; i++) {

      await new Promise(r => setTimeout(r, 3000));

      const progress = await axios.post(
        "https://api.seaart.io/v1/generate/progress",
        { task_ids: [taskId] },
        {
          headers: {
            token: token,
            "x-device-id": deviceId
          }
        }
      );

      const item = progress.data?.data?.items?.[0];

      if (item && item.status === "success" && item.images?.[0]?.url) {
        imageUrl = item.images[0].url;
        break;
      }

    }

    if (!imageUrl) {
      return await send({
        text: "❌ AI generation failed. Try a simpler prompt."
      });
    }

    // send image
    await sock.sendMessage(
      from,
      {
        image: { url: imageUrl },
        caption: `
🎨 AI IMAGE CREATION

✨ Prompt: ${prompt}

👤 Generated by: FLEX ZONE OFFICIAL

${config.footer}
`.trim(),
        contextInfo: {
          forwardingScore: 999,
          isForwarded: true,
          forwardedNewsletterMessageInfo: {
            newsletterJid: config.channelJid,
            newsletterName: config.botName
          }
        }
      },
      { quoted: msg }
    );

  } catch (err) {

    console.error("API Error:", err.message);

    await send({
      text: "❌ API error. Try again later."
    });

  }

};